# Generated by Django 2.2 on 2019-04-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookEngineApi', '0002_auto_20190420_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(default='Unread', max_length=10),
        ),
    ]
